### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by kjg**

### CODE REVIEW

**Comment by felixge** [comment]
@kjg awesome, thanks! I just added you as a collaborator to the repo. If you give me your npm user name, I'll also give you npm access.

**Comment by kjg** [comment]
Thanks! It says only repo admins can turn on travis, so can you please do so here https://travis-ci.org/felixge/node-stack-trace

**Comment by felixge** [comment]
@kjg I enabled it. Let me know your npm username if you want access to the npm pkg.

**Comment by kjg** [comment]
I just created my account https://www.npmjs.com/~kjg

**Comment by felixge** [comment]
Thanks, you should be able to publish new releases now if you want :)

**Comment by kjg** [comment]
Great. Thank you!

**Pull request merged**
